- hosts: localhost
  vars:
    - source_key: "~/.ssh/id_ed25519"
    - dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    - personal: "{{ lookup('env', 'HOME') }}/personal"
  pre_tasks:
    - name: Update apt
      become: true
      apt:
        upgrade: yes
        update_cache: true
        state: present
      tags:
        - core
  tasks:
    - include: tasks/ssh.yml
    - include: tasks/git-setup.yml
    - include: tasks/dotfiles.yml
