- name: Installing stow
  apt: name=stow
  tags:
    - dotfiles
- name: Cloning dotfiles
  ansible.builtin.git:
    repo: "git@github.com:FMGordillo/dotfiles.git"
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
  tags:
    - dotfiles
      #- name: Stow dotfiles
  # I have doubts about this command
  #shell: cd $HOME/dotfiles && ./ubuntu

